services:
  semestertable.api:
    image: semestertable.api
    container_name: semestertable.api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - semestertable.db

  semestertable.web:
    image: semestertable.web
    container_name: semestertable.web
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - semestertable.api
  
  semestertable.db:
    image: postgres:15-alpine
    container_name: semestertable.db
    environment:
      POSTGRES_DB: semestertable1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/semestertable1-db/:/var/lib/postgresql/data
    ports:
      - "5432:5432"